import {test,expect} from '@playwright/test';
test('same-scale orthographic inspection of actual person, car, scooter, door and floors',async({page},info)=>{
 test.skip(info.project.name!=='desktop','One controlled orthographic scale inspection; all layouts run normal gameplay.');
 await page.route('**/__proportion-inspection',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><meta charset="utf-8"><style>body{margin:0;color:#163a35;background:#e6ece8;font:16px sans-serif}header,footer{height:65px;box-sizing:border-box;padding:18px}canvas{display:block}</style><header>Actual game meshes · same orthographic camera · 10 world units = 1 metre · no Google Street View validation</header><canvas id="inspection"></canvas><footer id="summary"></footer>'}));await page.goto('/__proportion-inspection');
 const evidence=await page.evaluate(async()=>{
  const T=await import('/vendor/three.module.js'),models=await import('/src/models.js'),samples=await import('/src/sample-characters.js'),scale=await import('/src/scale.js'),xitun=await import('/src/world-xitun.js'),visuals=await import('/src/xitun-visuals.js');
  const scene=new T.Scene();scene.background=new T.Color(0xe6ece8);scene.add(new T.HemisphereLight(0xeaf4ff,0x687663,2.4));const sun=new T.DirectionalLight(0xffefcb,2.3);sun.position.set(-40,100,80);scene.add(sun);
  const renderer=new T.WebGLRenderer({canvas:document.querySelector('#inspection'),antialias:true,preserveDrawingBuffer:true});renderer.setSize(innerWidth,innerHeight-130);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;
  const camera=new T.OrthographicCamera(-100,100,(innerHeight-130)/innerWidth*100,-(innerHeight-130)/innerWidth*100,1,1000);camera.position.set(35,29,320);camera.lookAt(35,29,0);
  const bounds=group=>{group.updateMatrixWorld(true);const result=new T.Box3();group.traverseVisible(o=>{if(!o.isMesh)return;o.geometry.computeBoundingBox();result.union(o.geometry.boundingBox.clone().applyMatrix4(o.matrixWorld));});return result;};
  const walker=await samples.createSampleWalker('sunset'),scooter=await samples.createSampleScooter('sunset'),car=models.createCar({color:'#547d72'});models.setMountedRiderVisible(scooter,false);walker.rotation.y=Math.PI/2;
  const actual={};for(const [id,g,x]of [['person',walker,-46],['scooter',scooter,-22],['car',car,14]]){const b=bounds(g);actual[id]=b.getSize(new T.Vector3()).toArray().map(v=>v/10);g.position.y=-b.min.y;g.position.x=x;scene.add(g);}
  const world=xitun.createSceneWorld(),proxy={...world.buildings.find(b=>b.kind==='hospital'),kind:'block',x:70,y:0,w:60,d:35,floorCount:2,h:62,height:62,sign:'2.2m door / 3m floor'};scene.add(visuals.createXitunCity({...world,buildings:[proxy],stalls:[],trees:[],lamps:[]}).city);
  const ruler=(x,top,color)=>{const points=[new T.Vector3(x,0,38),new T.Vector3(x,top,38),new T.Vector3(x+2,top,38)];scene.add(new T.Line(new T.BufferGeometry().setFromPoints(points),new T.LineBasicMaterial({color})));};ruler(-51,scale.PERSON.height,0x426b50);ruler(100,scale.BUILDING.doorHeight,0xa5653c);ruler(134,scale.BUILDING.groundFloorHeight,0x52717e);ruler(134,62,0x52717e);
  renderer.render(scene,camera);const gl=renderer.getContext(),debug=gl.getExtension('WEBGL_debug_renderer_info');
  const personHeight=actual.person[1],metrics={person:{target:1.72,actualHeight:personHeight,deviationPercent:(personHeight/1.72-1)*100},car:{targetHeight:1.5,targetLength:4.4,actualHeight:actual.car[1],actualLength:actual.car[0],heightToPersonPercent:actual.car[1]/personHeight*100},scooter:{targetLength:2,actualLength:actual.scooter[0],lengthToPersonPercent:actual.scooter[0]/personHeight*100},door:{height:scale.BUILDING.doorHeight/10,targetToPersonPercent:scale.BUILDING.doorHeight/scale.PERSON.height*100},floor:{upperHeight:3,groundHeight:3.2,targetToPersonPercent:scale.BUILDING.upperFloorHeight/scale.PERSON.height*100}};
  document.querySelector('#summary').textContent=`Visible mesh: person ${personHeight.toFixed(3)}m | car ${actual.car[1].toFixed(3)}m high / ${actual.car[0].toFixed(3)}m long | scooter ${actual.scooter[0].toFixed(3)}m | door 2.2m | upper floor 3m`;
  return {gpu:gl.getParameter(debug.UNMASKED_RENDERER_WEBGL),browser:navigator.userAgent,projection:'orthographic, identical scale; lowest visible point aligned to floor without resizing',unitsPerMetre:10,metrics,googleMapsVisualChecked:false,error:gl.getError()};
 });expect(evidence.error).toBe(0);expect(evidence.metrics.door.height).toBe(2.2);expect(evidence.metrics.floor.upperHeight).toBe(3);expect(evidence.metrics.person.actualHeight).toBeGreaterThan(1.6);expect(evidence.metrics.car.actualLength).toBeLessThanOrEqual(4.4);
 const path=info.outputPath('relative-proportions.png');await page.screenshot({path,fullPage:true});await info.attach('relative-proportions',{path,contentType:'image/png'});await info.attach('relative-proportion-evidence',{body:JSON.stringify(evidence,null,2),contentType:'application/json'});
});
