import {test,expect} from '@playwright/test';
import {startJourney} from './controls.mjs';
const snapshot=page=>page.evaluate(()=>window.taipeiRide.snapshot());
async function seed(page,raw={}){
 await page.addInitScript(raw=>{if(sessionStorage.getItem('scene-test-seeded'))return;sessionStorage.setItem('scene-test-seeded','1');localStorage.setItem('taipei-ride:v2',JSON.stringify({version:2,player:{x:800,y:515,angle:-Math.PI/2,distance:123},vehicle:{x:800,y:515,angle:-Math.PI/2},mode:'riding',stamps:['tower'],quest:{stage:'carrying',rideDistance:10,rewardClaimed:false},activity:'explore',night:true,coins:77,selectedLandmark:'market',...raw}));},raw);
}
async function switchTo(page,id){await page.locator('#scene-switch').click();await page.locator(`[data-scene="${id}"]`).click();await expect.poll(async()=>{const s=await snapshot(page);return !s.scene.loading&&s.scene.id===id&&!s.paused;}).toBe(true);}
async function capture(page,info,name){const path=info.outputPath(`${name}.png`);await page.screenshot({path,fullPage:true});await info.attach(name,{path,contentType:'image/png'});}

test('scene switching releases maps, retains progress and modes, reloads Xitun and clears held input',async({page},info)=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await seed(page);await page.goto('/?sample=refined');await startJourney(page);
 await expect.poll(async()=>(await snapshot(page)).view.sample.ready).toBe(true);
 await page.keyboard.press('f');await expect.poll(async()=>(await snapshot(page)).mode).toBe('walking');
 await switchTo(page,'xitun');let s=await snapshot(page);expect(s.activity).toBe('explore');expect(s.coins).toBe(77);expect(s.night).toBe(true);expect(s.stamps).toEqual([]);expect(s.mode).toBe('walking');expect(s.scene.lastDisposal.geometries).toBeGreaterThan(0);expect(s.scene.landmarks).toHaveLength(5);
 await expect(page.locator('#stamp-count')).toHaveText('0 / 5');await expect(page.locator('#cargo-status')).toBeHidden();await page.locator('#open-map').click();await expect(page.locator('#track-quest')).toBeHidden();await expect(page.locator('#map-note')).toContainText('縮比例');await capture(page,info,'xitun-map');await page.locator('#map-dialog [data-close]').click();
 await page.keyboard.press('r');expect((await snapshot(page)).player.x).toBe(1080);await page.keyboard.down('w');await page.locator('#scene-switch').click();await page.locator('[data-scene="taipei"]').click();await expect.poll(async()=>(await snapshot(page)).scene.id).toBe('taipei');await page.keyboard.up('w');
 s=await snapshot(page);expect(s.stamps).toEqual(['tower']);expect(s.quest.stage).toBe('carrying');expect(s.quest.rideDistance).toBe(10);expect(s.coins).toBe(77);await expect(page.locator('#stamp-count')).toHaveText('1 / 6');
 const x=s.player.x,y=s.player.y;await page.waitForTimeout(350);s=await snapshot(page);expect(Math.hypot(s.player.x-x,s.player.y-y)).toBeLessThan(.1);
 const memory=[];for(let i=0;i<6;i++){await switchTo(page,i%2?'taipei':'xitun');await expect.poll(async()=>(await snapshot(page)).view.sample.ready).toBe(true);await page.waitForTimeout(150);s=await snapshot(page);memory.push({id:s.scene.id,...s.scene.resources,disposed:s.scene.lastDisposal});expect(s.renderMode).toBe('3d');}
 for(const id of ['taipei','xitun']){const rows=memory.filter(m=>m.id===id);expect(Math.max(...rows.map(m=>m.geometries))-Math.min(...rows.map(m=>m.geometries))).toBeLessThan(3);expect(Math.max(...rows.map(m=>m.textures))-Math.min(...rows.map(m=>m.textures))).toBeLessThan(3);}
 await info.attach('scene-resource-cycles',{body:JSON.stringify(memory,null,2),contentType:'application/json'});
 await switchTo(page,'xitun');await page.reload();await page.waitForFunction(()=>Boolean(window.taipeiRide));await expect.poll(async()=>(await snapshot(page)).scene.id).toBe('xitun');await startJourney(page);await capture(page,info,'xitun-entry');expect(errors).toEqual([]);
});

test('first on-demand map load can be cancelled without losing Taipei or leaving input active',async({page})=>{
 await seed(page);let release;const gate=new Promise(resolve=>release=resolve);await page.route('**/src/world-xitun.js*',async route=>{await gate;await route.continue();});
 await page.goto('/?sample=refined');await startJourney(page);await page.locator('#scene-switch').click();await page.locator('[data-scene="xitun"]').click();await expect.poll(async()=>(await snapshot(page)).scene.loading).toBe(true);await page.keyboard.press('Escape');release();await expect.poll(async()=>(await snapshot(page)).scene.loading).toBe(false);expect((await snapshot(page)).scene.id).toBe('taipei');expect((await snapshot(page)).stamps).toEqual(['tower']);await switchTo(page,'xitun');expect((await snapshot(page)).renderMode).toBe('3d');
});

test('Taiwan Boulevard is driven continuously past hospital to Prosperity with live traffic',async({page},info)=>{
 test.skip(info.project.name!=='desktop','Long drive once; switching and layout run in all viewports.');
 await seed(page);await page.goto('/?sample=refined');await startJourney(page);await switchTo(page,'xitun');await page.keyboard.press('n');await expect.poll(async()=>(await snapshot(page)).view.sample.ready).toBe(true);await capture(page,info,'taiwan-boulevard-entry');
 await page.locator('#open-map').click();await page.locator('#map-destinations button').filter({hasText:'澄清醫院'}).click();await page.keyboard.down('w');await expect.poll(async()=>(await snapshot(page)).player.x,{timeout:45000}).toBeLessThan(645);await page.keyboard.down('Space');await page.keyboard.up('w');await expect.poll(async()=>Math.abs((await snapshot(page)).player.speed)).toBeLessThan(.3);await page.keyboard.up('Space');await page.mouse.move(650,510);await page.mouse.down();await page.mouse.move(1043,590,{steps:10});await page.mouse.up();await page.waitForTimeout(250);await capture(page,info,'cheng-ching-hospital');await page.mouse.move(1043,590);await page.mouse.down();await page.mouse.move(650,510,{steps:10});await page.mouse.up();await page.keyboard.press('e');await expect(page.locator('#stamp-dialog')).toBeVisible();await page.locator('#next-stop').click();
 await page.locator('#open-map').click();await page.locator('#map-destinations button').filter({hasText:'萬家福'}).click();await page.keyboard.down('w');await expect.poll(async()=>(await snapshot(page)).player.x,{timeout:45000}).toBeLessThan(365);await page.keyboard.down('Space');await page.keyboard.up('w');await expect.poll(async()=>Math.abs((await snapshot(page)).player.speed)).toBeLessThan(.3);await page.keyboard.up('Space');await page.mouse.move(650,510);await page.mouse.down();await page.mouse.move(1043,590,{steps:10});await page.mouse.up();await page.waitForTimeout(250);await capture(page,info,'prosperity-xitun');await page.keyboard.press('e');await expect(page.locator('#stamp-dialog')).toBeVisible();expect((await snapshot(page)).stamps).toEqual(['xitun-hospital','xitun-store']);await page.locator('#next-stop').click();
 const evidence=await page.evaluate(async()=>{const deltas=[];let last;await new Promise(resolve=>{function sample(t){if(last)deltas.push(t-last);last=t;if(deltas.length===120)resolve();else requestAnimationFrame(sample);}requestAnimationFrame(sample);});const canvas=document.querySelector('#world'),gl=canvas.getContext('webgl2'),debug=gl.getExtension('WEBGL_debug_renderer_info');const mean=deltas.reduce((a,b)=>a+b,0)/deltas.length;return {browser:navigator.userAgent,gpu:gl.getParameter(debug.UNMASKED_RENDERER_WEBGL),css:[innerWidth,innerHeight],buffer:[gl.drawingBufferWidth,gl.drawingBufferHeight],fps:1000/mean,frameTimeMs:mean,state:window.taipeiRide.snapshot()};});await info.attach('xitun-native-frame-evidence',{body:JSON.stringify(evidence,null,2),contentType:'application/json'});expect(evidence.gpu).toBeTruthy();
});

test('failed on-demand load keeps Taipei and can be retried without a page reload',async({page})=>{
 await seed(page);let fail=true;await page.route('**/src/world-xitun.js*',async route=>{if(fail){fail=false;await route.abort('failed');}else await route.continue();});
 await page.goto('/?sample=refined');await startJourney(page);await page.locator('#scene-switch').click();await page.locator('[data-scene="xitun"]').click();await expect(page.locator('#toast')).toContainText('地區載入失敗');expect((await snapshot(page)).scene.id).toBe('taipei');expect((await snapshot(page)).stamps).toEqual(['tower']);await switchTo(page,'xitun');expect((await snapshot(page)).renderMode).toBe('3d');
});

for(const [id,name,x,y,angle]of [['xitun-autumn','autumn-valley',1120,935,Math.PI],['xitun-opera','national-theater',1290,1120,Math.PI/2],['xitun-fengjia','fengjia-market',1440,365,Math.PI]])test(`Xitun ${name} renders recognizable geometry and consistent HUD`,async({page},info)=>{
 await seed(page,{sceneId:'xitun',player:{x,y,angle,distance:0},vehicle:{x,y,angle},stamps:[],selectedLandmark:id,night:false});await page.goto('/?sample=refined');await startJourney(page);await expect.poll(async()=>(await snapshot(page)).view.sample.ready).toBe(true);expect((await snapshot(page)).target).toBe(id);expect((await snapshot(page)).renderMode).toBe('3d');await page.waitForTimeout(300);await capture(page,info,name);await page.keyboard.press('e');await expect(page.locator('#stamp-dialog')).toBeVisible();expect((await snapshot(page)).stamps).toEqual([id]);
});

test('2D fallback can switch both maps, preserves walker separation and resets to the local entrance',async({page})=>{
 await seed(page);await page.goto('/?renderer=2d');await startJourney(page);await switchTo(page,'xitun');expect((await snapshot(page)).renderMode).toBe('2d');await page.keyboard.press('f');expect((await snapshot(page)).mode).toBe('walking');await page.keyboard.press('r');expect((await snapshot(page)).player.x).toBe(1080);await switchTo(page,'taipei');expect((await snapshot(page)).player.x).toBe(800);expect((await snapshot(page)).stamps).toEqual(['tower']);
});

test('interrupted saved Xitun restore falls back to Taipei without erasing either city',async({page})=>{
 const city=id=>({version:2,mode:'walking',stamps:[id],player:{x:800,y:515,angle:0,distance:123},vehicle:{x:800,y:515,angle:0},coins:77,activity:'explore',quest:{stage:'pickup',rideDistance:0,rewardClaimed:false}});
 await seed(page,{sceneId:'xitun',cityStates:{taipei:city('tower'),xitun:city('xitun-store')}});let fail=true;await page.route('**/src/world-xitun.js*',async route=>{if(fail){fail=false;await route.abort('failed');}else await route.continue();});await page.goto('/?sample=refined');await startJourney(page);expect((await snapshot(page)).scene.id).toBe('taipei');expect((await snapshot(page)).stamps).toEqual(['tower']);await switchTo(page,'xitun');expect((await snapshot(page)).stamps).toEqual(['xitun-store']);await switchTo(page,'taipei');expect((await snapshot(page)).quest.stage).toBe('pickup');expect((await snapshot(page)).mode).toBe('walking');
});

test('late character assets after scene disposal cannot resurrect the departed renderer',async({page})=>{
 await seed(page);const errors=[];page.on('pageerror',error=>errors.push(error.message));let release;const gate=new Promise(resolve=>release=resolve);await page.route('**/public/sample/*.json',async route=>{await gate;await route.continue();});await page.goto('/?sample=refined');await startJourney(page);expect((await snapshot(page)).view.sample.ready).toBe(false);await switchTo(page,'xitun');release();await expect.poll(async()=>(await snapshot(page)).view.sample.ready).toBe(true);await page.waitForTimeout(300);expect((await snapshot(page)).scene.id).toBe('xitun');expect((await snapshot(page)).scene.switches).toBe(1);expect(await page.evaluate(()=>document.querySelector('#world').getContext('webgl2').getError())).toBe(0);await switchTo(page,'taipei');await expect.poll(async()=>(await snapshot(page)).view.sample.ready).toBe(true);expect(errors).toEqual([]);
});
