import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import * as T from '../vendor/three.module.js';
import {sweptGarment} from '../src/models.js';
import {createSampleCharacter,createSampleScooter,animateSampleWalker} from '../src/sample-characters.js';
const walker=JSON.parse(await readFile(new URL('../public/sample/walker.json',import.meta.url))),rider=JSON.parse(await readFile(new URL('../public/sample/rider.json',import.meta.url)));
function boundaries(part){const p=part.positions,positions=Array.from({length:p.length/3},(_,i)=>p.slice(i*3,i*3+3).join(',')),edges=new Map();for(let i=0;i<part.indices.length;i+=3){const f=part.indices.slice(i,i+3);for(const[a,b]of[[f[0],f[1]],[f[1],f[2]],[f[2],f[0]]]){const key=[positions[a],positions[b]].sort().join('|');edges.set(key,(edges.get(key)||0)+1);}}const adjacency=new Map();for(const[edge,count]of edges)if(count===1){const[a,b]=edge.split('|');for(const[x,y]of[[a,b],[b,a]]){if(!adjacency.has(x))adjacency.set(x,[]);adjacency.get(x).push(y);}}const remaining=new Set(adjacency.keys());let loops=0;while(remaining.size){const stack=[remaining.values().next().value];loops++;while(stack.length){const n=stack.pop();if(!remaining.delete(n))continue;stack.push(...adjacency.get(n));}}return {loops,edges:adjacency.size,branches:[...adjacency.values()].filter(n=>n.length!==2).length};}
test('folded legacy garment closes every ring, including the reported half-way slit',()=>{const g=sweptGarment([[0,0,0],[0,1,0]],[[.5,.5],[.5,.5]],true),p=g.attributes.position;for(let j=0;j<=24;j++){const a=new T.Vector3().fromBufferAttribute(p,j*13),b=new T.Vector3().fromBufferAttribute(p,j*13+12);assert.ok(a.distanceTo(b)<1e-6);}});
test('sample CC0 anatomical meshes retain valid finite topology and normalized skinning',()=>{for(const data of[walker,rider]){assert.equal(data.license,'CC0-1.0');assert.match(data.sourceSHA256,/^[a-f0-9]{64}$/);for(const m of data.meshes){assert.ok(m.positions.every(Number.isFinite));assert.equal(m.normals.length,m.positions.length);assert.equal(m.skinWeights.length,m.positions.length/3*4);assert.ok(m.indices.every(i=>i>=0&&i<m.positions.length/3));for(let i=0;i<m.skinWeights.length;i+=4){assert.ok(Math.abs(m.skinWeights.slice(i,i+4).reduce((a,b)=>a+b,0)-1)<.000003);assert.ok(m.skinIndices.slice(i,i+4).every(n=>n<data.bones.length));}}}});
test('one continuous shirt has only neck, two cuffs and hem boundaries; trousers only waist and ankles',()=>{for(const data of[walker,rider])for(const[material,count]of[['jacket',4],['denim',3]]){const b=boundaries(data.meshes.find(m=>m.material===material));assert.equal(b.loops,count);assert.equal(b.branches,0);}});
test('footwear follows actual skinned foot bones through repeated animated strides',()=>{const g=createSampleCharacter(walker),bones=g.userData.bones;g.updateMatrixWorld(true);const initial={};for(const side of['l','r']){const bone=bones.find(b=>b.name===side+'-foot'),shoe=bone.getObjectByName('sample-sneaker');assert.equal(shoe.parent,bone);initial[side]=shoe.getWorldPosition(new T.Vector3());}let maximumTravel=0;for(let step=0;step<80;step++){animateSampleWalker(g,step*.07,14);g.updateMatrixWorld(true);for(const side of['l','r']){const bone=bones.find(b=>b.name===side+'-foot'),shoe=bone.getObjectByName('sample-sneaker'),expected=bone.localToWorld(shoe.position.clone());assert.ok(expected.distanceTo(shoe.getWorldPosition(new T.Vector3()))<1e-6);maximumTravel=Math.max(maximumTravel,initial[side].distanceTo(shoe.getWorldPosition(new T.Vector3())));}}assert.ok(maximumTravel>1);});
test('seated soles remain on the existing floorboards and fingers curl around both production grips',()=>{const group=createSampleCharacter(rider,{mounted:true});group.updateMatrixWorld(true);for(const side of[-1,1]){const shoe=group.userData.bones.find(b=>b.name===(side<0?'l':'r')+'-foot').getObjectByName('sample-sneaker'),bounds=new T.Box3().setFromObject(shoe);assert.ok(Math.abs(bounds.min.y-3.06)<.04);const p=rider.meshes.find(m=>m.material==='skin').positions;let closest=Infinity;for(let i=0;i<p.length;i+=3){const dx=p[i]-5.7,dy=p[i+1]-11.25,dz=p[i+2]-side*3.65;closest=Math.min(closest,Math.hypot(dx,dy,dz));}assert.ok(closest<.33,`skin/grip distance ${closest}`);}});
test('sample complete scooter stays inside the established footprint and batches its PBR surfaces',async()=>{const originalFetch=globalThis.fetch;globalThis.fetch=async url=>({ok:true,json:async()=>JSON.parse(await readFile(url))});try{const g=await createSampleScooter();g.updateMatrixWorld(true);const bounds=new T.Box3();let calls=0;g.traverseVisible(o=>{if(!o.isMesh)return;calls++;o.geometry.computeBoundingBox();bounds.union(o.geometry.boundingBox.clone().applyMatrix4(o.matrixWorld));});assert.ok(bounds.min.x>=-10&&bounds.max.x<=10.01);assert.ok(bounds.min.z>=-4.3&&bounds.max.z<=4.3);assert.ok(calls<=35,`draw meshes ${calls}`);const lens=new T.Raycaster(new T.Vector3(12,11.47,0),new T.Vector3(-1,0,0)).intersectObject(g,true)[0];assert.ok(lens.point.x>6.85,'the lens must cover the painted cowl, not intersect behind it');assert.equal(lens.object.material.roughness,.13);}finally{globalThis.fetch=originalFetch;}});
test('standing hand skin stays outside trousers rather than disappearing into the hips',()=>{const data=walker.meshes.find(m=>m.material==='denim'),g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(data.positions,3));g.setIndex(data.indices);const trousers=new T.Mesh(g,new T.MeshBasicMaterial({side:T.DoubleSide})),p=walker.meshes.find(m=>m.material==='skin').positions;let compared=0;for(let i=0;i<p.length;i+=3){const[x,y,z]=p.slice(i,i+3);if(y>=8.5)continue;const side=Math.sign(z),hit=new T.Raycaster(new T.Vector3(x,y,side*10),new T.Vector3(0,0,-side)).intersectObject(trousers)[0];if(!hit)continue;compared++;assert.ok(Math.abs(z)>=Math.abs(hit.point.z)-.01,`hand at ${x},${y},${z} penetrates the trouser surface ${hit.point.z}`);}assert.ok(compared>100);for(const m of walker.meshes)for(let i=0;i<m.positions.length;i+=3)assert.ok(Math.hypot(m.positions[i],m.positions[i+2])<=2.6,'standing sample stays in the existing collision circle');});
test('accessories are batched per moving bone and mounted body avoids unnecessary skinning',()=>{for(const mounted of[false,true]){const g=createSampleCharacter(mounted?rider:walker,{mounted});let calls=0,skinned=0,triangles=0;g.traverseVisible(o=>{if(!o.isMesh)return;calls++;skinned+=!!o.isSkinnedMesh;triangles+=(o.geometry.index?.count||o.geometry.attributes.position.count)/3;});assert.ok(calls<=(mounted?14:12),`${calls} hero draw calls`);assert.equal(skinned,mounted?0:4);assert.ok(triangles>20000,'anatomical detail has not been removed to satisfy the draw budget');}});
test('animated hands remain outside moving trousers throughout representative gait phases',()=>{const g=createSampleCharacter(walker),skin=g.getObjectByName('walking-skin'),pants=g.getObjectByName('walking-denim');for(const time of[.08,.2,.38,.6]){animateSampleWalker(g,time,14);g.updateMatrixWorld(true);const positions=[];for(let i=0;i<pants.geometry.attributes.position.count;i++)positions.push(...pants.getVertexPosition(i,new T.Vector3()).toArray());const geometry=pants.geometry.clone();geometry.setAttribute('position',new T.Float32BufferAttribute(positions,3));geometry.computeBoundingSphere();const trousers=new T.Mesh(geometry,new T.MeshBasicMaterial({side:T.DoubleSide}));for(let i=0;i<skin.geometry.attributes.position.count;i++){if(skin.geometry.attributes.position.getY(i)>=8.5)continue;const p=skin.getVertexPosition(i,new T.Vector3()),side=Math.sign(p.z),hit=new T.Raycaster(new T.Vector3(p.x,p.y,side*10),new T.Vector3(0,0,-side)).intersectObject(trousers)[0];if(hit)assert.ok(Math.abs(p.z)>=Math.abs(hit.point.z)-.01,`gait ${time} hand intersects thigh`);}geometry.dispose();trousers.material.dispose();}});

test('optimized footwear keeps sole, upper and lace colors in one indexed draw per foot',()=>{
 const g=createSampleCharacter(walker);
 for(const side of ['l','r']){
  const shoe=g.userData.bones.find(b=>b.name===side+'-foot').getObjectByName('sample-sneaker');
  assert.equal(shoe.children.length,1);
  const mesh=shoe.children[0];assert.ok(mesh.geometry.index);assert.ok(mesh.material.vertexColors);
  const c=mesh.geometry.attributes.color;const colors=new Set();
  for(let i=0;i<c.count;i++)colors.add([c.getX(i),c.getY(i),c.getZ(i)].join(','));
  assert.equal(colors.size,3,'sole, upper and lace remain distinguishable');
 }
 let calls=0;g.traverseVisible(o=>{if(o.isMesh)calls++;});assert.equal(calls,8);
 for(const part of walker.meshes){
  const mesh=g.getObjectByName(part.name);
  assert.deepEqual(Array.from(mesh.geometry.index.array),part.indices,'anatomical topology is unchanged');
 }
});

test('mounted anatomical meshes omit unused GPU skin buffers while preserving their original vertices',()=>{
 const g=createSampleCharacter(rider,{mounted:true});
 for(const part of rider.meshes){const mesh=g.getObjectByName(part.name);assert.equal(mesh.geometry.attributes.skinWeight,undefined);assert.equal(mesh.geometry.attributes.skinIndex,undefined);assert.equal(mesh.geometry.attributes.position.count,part.positions.length/3);assert.deepEqual(Array.from(mesh.geometry.index.array),part.indices);}
});
