import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import * as T from '../vendor/three.module.js';
import {sweptGarment} from '../src/models.js';
import {createSampleCharacter,createSampleScooter,animateSampleWalker} from '../src/sample-characters.js';
const walker=JSON.parse(await readFile(new URL('../public/sample/walker.json',import.meta.url))),rider=JSON.parse(await readFile(new URL('../public/sample/rider.json',import.meta.url)));
function boundaries(part){const p=part.positions,positions=Array.from({length:p.length/3},(_,i)=>p.slice(i*3,i*3+3).join(',')),edges=new Map();for(let i=0;i<part.indices.length;i+=3){const f=part.indices.slice(i,i+3);for(const[a,b]of[[f[0],f[1]],[f[1],f[2]],[f[2],f[0]]]){const key=[positions[a],positions[b]].sort().join('|');edges.set(key,(edges.get(key)||0)+1);}}const adjacency=new Map();for(const[edge,count]of edges)if(count===1){const[a,b]=edge.split('|');for(const[x,y]of[[a,b],[b,a]]){if(!adjacency.has(x))adjacency.set(x,[]);adjacency.get(x).push(y);}}const remaining=new Set(adjacency.keys());let loops=0;while(remaining.size){const stack=[remaining.values().next().value];loops++;while(stack.length){const n=stack.pop();if(!remaining.delete(n))continue;stack.push(...adjacency.get(n));}}return {loops,edges:adjacency.size,branches:[...adjacency.values()].filter(n=>n.length!==2).length};}
test('folded legacy garment closes every ring, including the reported half-way slit',()=>{const g=sweptGarment([[0,0,0],[0,1,0]],[[.5,.5],[.5,.5]],true),p=g.attributes.position;for(let j=0;j<=24;j++){const a=new T.Vector3().fromBufferAttribute(p,j*13),b=new T.Vector3().fromBufferAttribute(p,j*13+12);assert.ok(a.distanceTo(b)<1e-6);}});
test('sample CC0 anatomical meshes retain valid finite topology and normalized skinning',()=>{for(const data of[walker,rider]){assert.equal(data.license,'CC0-1.0');assert.match(data.sourceSHA256,/^[a-f0-9]{64}$/);for(const m of data.meshes){assert.ok(m.positions.every(Number.isFinite));assert.equal(m.normals.length,m.positions.length);assert.equal(m.skinWeights.length,m.positions.length/3*4);assert.ok(m.indices.every(i=>i>=0&&i<m.positions.length/3));for(let i=0;i<m.skinWeights.length;i+=4){assert.ok(Math.abs(m.skinWeights.slice(i,i+4).reduce((a,b)=>a+b,0)-1)<.000003);assert.ok(m.skinIndices.slice(i,i+4).every(n=>n<data.bones.length));}}}});
test('one continuous shirt has only neck, two cuffs and hem boundaries; trousers only waist and ankles',()=>{for(const data of[walker,rider])for(const[material,count]of[['jacket',4],['denim',3]]){const b=boundaries(data.meshes.find(m=>m.material===material));assert.equal(b.loops,count);assert.equal(b.branches,0);}});
test('footwear follows actual skinned foot bones through repeated animated strides',()=>{const g=createSampleCharacter(walker),bones=g.userData.bones;g.updateMatrixWorld(true);const initial={};for(const side of['l','r']){const bone=bones.find(b=>b.name===side+'-foot'),shoe=bone.getObjectByName('sample-sneaker');assert.equal(shoe.parent,bone);initial[side]=shoe.getWorldPosition(new T.Vector3());}let maximumTravel=0;for(let step=0;step<80;step++){animateSampleWalker(g,step*.07,14);g.updateMatrixWorld(true);for(const side of['l','r']){const bone=bones.find(b=>b.name===side+'-foot'),shoe=bone.getObjectByName('sample-sneaker'),expected=bone.localToWorld(shoe.position.clone());assert.ok(expected.distanceTo(shoe.getWorldPosition(new T.Vector3()))<1e-6);maximumTravel=Math.max(maximumTravel,initial[side].distanceTo(shoe.getWorldPosition(new T.Vector3())));}}assert.ok(maximumTravel>1);});
test('seated soles remain on the existing floorboards and fingers curl around both production grips',()=>{const group=createSampleCharacter(rider,{mounted:true});group.updateMatrixWorld(true);for(const side of[-1,1]){const shoe=group.userData.bones.find(b=>b.name===(side<0?'l':'r')+'-foot').getObjectByName('sample-sneaker'),bounds=new T.Box3().setFromObject(shoe);assert.ok(Math.abs(bounds.min.y-3.06)<.04);const p=rider.meshes.find(m=>m.material==='skin').positions;let closest=Infinity;for(let i=0;i<p.length;i+=3){const dx=p[i]-5.7,dy=p[i+1]-11.25,dz=p[i+2]-side*3.65;closest=Math.min(closest,Math.hypot(dx,dy,dz));}assert.ok(closest<.33,`skin/grip distance ${closest}`);}});
test('sample complete scooter stays inside the established footprint and batches its PBR surfaces',async()=>{const originalFetch=globalThis.fetch;globalThis.fetch=async url=>({ok:true,json:async()=>JSON.parse(await readFile(url))});try{const g=await createSampleScooter();g.updateMatrixWorld(true);const bounds=new T.Box3();let calls=0;g.traverseVisible(o=>{if(!o.isMesh)return;calls++;o.geometry.computeBoundingBox();bounds.union(o.geometry.boundingBox.clone().applyMatrix4(o.matrixWorld));});assert.ok(bounds.min.x>=-10&&bounds.max.x<=10.01);assert.ok(bounds.min.z>=-4.3&&bounds.max.z<=4.3);assert.ok(calls<=35,`draw meshes ${calls}`);const lens=new T.Raycaster(new T.Vector3(12,11.47,0),new T.Vector3(-1,0,0)).intersectObject(g,true)[0];assert.ok(lens.point.x>6.85,'the lens must cover the painted cowl, not intersect behind it');assert.equal(lens.object.material.roughness,.13);}finally{globalThis.fetch=originalFetch;}});
