// Original diagrams document only controls implemented by this game.
const TEXT = {
 zh: {tabs:['鍵盤滑鼠','手把','觸控'],move:'移動 / 駕駛',actions:'互動',menus:'介面',foot:'步行',ride:'騎乘',interface:'介面',forward:'前進 / 油門',back:'後退 / 倒車',left:'左轉',right:'右轉',interact:'互動',vehicle:'上下車',reset:'安全回起點',night:'日夜',map:'地圖',pause:'暫停',brake:'煞車',look:'拖曳調整視角',mouse:'按住左鍵或右鍵拖曳',unused:'灰色鍵沒有遊戲操作',movement:'移動 / 轉向',camera:'視角（3D）',return:'返回 / 跳過開場',touch:'按住方向鍵與油門可同時轉彎；放開、取消觸控或切換視窗就會停止輸入。',gamepad:'支援標準配置手把。瀏覽器辨識後，先按一下任意按鈕啟用。',noCombat:'此版本專注城市探索與送茶委託，沒有武器、攻擊或跳躍操作。',note:'停穩才能下車；步行靠近停放的機車才能上車。'},
 en: {tabs:['Keyboard & mouse','Gamepad','Touch'],move:'MOVE / DRIVE',actions:'ACTIONS',menus:'INTERFACE',foot:'ON FOOT',ride:'RIDING',interface:'INTERFACE',forward:'Forward / throttle',back:'Back / reverse',left:'Turn left',right:'Turn right',interact:'Interact',vehicle:'Get on / off',reset:'Return safely to start',night:'Day / night',map:'Map',pause:'Pause',brake:'Brake',look:'Drag to look',mouse:'Hold either mouse button and drag',unused:'Dim keys have no game action',movement:'Move / steer',camera:'Look (3D)',return:'Back / skip intro',touch:'Hold steering and throttle together to turn. Releasing, cancelling touch or leaving the window clears the input.',gamepad:'Standard-mapping controllers are supported. Press any controller button to activate it in your browser.',noCombat:'This version focuses on exploration and tea deliveries. Weapons, attacks and jumping are not implemented.',note:'Stop before getting off. Walk close to the parked scooter to get back on.'}
};
const rows = [['Esc','P'],['Tab','Q','W','E','R','T'],['A','S','D','F','G','H'],['Shift','Z','X','C','V','B','N','M'],['Space']];
const actions = {Esc:['pause','ui'],P:['pause','ui'],W:['forward','move'],A:['left','move'],S:['back','move'],D:['right','move'],E:['interact','action'],F:['vehicle','action'],R:['reset','vehicle'],N:['night','ui'],M:['map','ui'],Space:['brake','vehicle']};
function key(label, caption = '', type = 'unused') { return `<div class="diagram-key key-${type} ${label==='Space'?'space-key':''} ${label==='Shift'||label==='Tab'?'wide-key':''}"><b>${label}</b><span>${caption}</span></div>`; }
function mapping(label, keys) { return `<div class="control-mapping"><span>${label}</span><span>${keys.map(k=>`<kbd>${k}</kbd>`).join('')}</span></div>`; }
export function initControlsPanel(container, language = 'zh') {
 let currentLanguage = language === 'en' ? 'en' : 'zh', tab = 0;
 function select(index, focus = false) {
  tab = (index+3)%3;
  container.querySelectorAll('[role=tab]').forEach((button,i)=>{button.setAttribute('aria-selected',String(i===tab));button.tabIndex=i===tab?0:-1;if(i===tab&&focus)button.focus();});
  container.querySelectorAll('[role=tabpanel]').forEach((panel,i)=>panel.hidden=i!==tab);
 }
 function render() {
  const t=TEXT[currentLanguage];
  container.innerHTML=`<div class="controls-tabs" role="tablist" aria-label="${currentLanguage==='zh'?'操作裝置':'Input device'}">${t.tabs.map((label,i)=>`<button role="tab" id="control-tab-${i}" aria-controls="control-panel-${i}">${label}</button>`).join('')}</div>
   <section id="control-panel-0" role="tabpanel" aria-labelledby="control-tab-0"><div class="keyboard-mouse-figure"><div class="keyboard-diagram" aria-label="${t.tabs[0]}">${rows.map((row,i)=>`<div class="keyboard-row keyboard-row-${i}">${row.map(label=>key(label,actions[label]?t[actions[label][0]]:'',actions[label]?.[1])).join('')}</div>`).join('')}<div class="keyboard-legend"><span class="legend-move">${t.move}</span><span class="legend-action">${t.actions}</span><span class="legend-ui">${t.menus}</span></div></div><div class="mouse-diagram"><div class="mouse-body"><span>${t.look}</span><i></i></div><small>${t.mouse}</small></div></div><p class="controls-caption">${t.unused}</p>
   <div class="controls-section-title">${t.foot} <small>ON FOOT</small></div><div class="controls-mapping-grid">${mapping(t.movement,['W','A','S','D'])}${mapping(t.camera,[currentLanguage==='zh'?'滑鼠拖曳':'Mouse drag'])}${mapping(t.interact,['E'])}${mapping(t.vehicle,['F'])}</div>
   <div class="controls-section-title">${t.ride} <small>RIDING · SCOOTER</small></div><div class="controls-mapping-grid">${mapping(t.forward,['W','↑'])}${mapping(t.back,['S','↓'])}${mapping(t.movement,['A','D','←','→'])}${mapping(t.brake,['Space'])}</div>
   <div class="controls-section-title">${t.interface} <small>MENUS</small></div><div class="controls-mapping-grid">${mapping(t.map,['M'])}${mapping(t.pause,['Esc','P'])}${mapping(t.night,['N'])}${mapping(t.reset,['R'])}</div></section>
   <section id="control-panel-1" role="tabpanel" aria-labelledby="control-tab-1" hidden><div class="gamepad-diagram" aria-label="${t.tabs[1]}"><div class="gamepad-trigger left">LT<br><small>${t.brake}</small></div><div class="gamepad-trigger right">RT<br><small>${t.forward}</small></div><div class="gamepad-shell"><div class="gamepad-stick left">L<br><small>${t.movement}</small></div><div class="gamepad-center"><span>View</span><span>Start</span></div><div class="gamepad-buttons"><b class="pad-y">Y</b><b class="pad-x">X</b><b class="pad-b">B</b><b class="pad-a">A</b></div><div class="gamepad-stick right">R<br><small>${t.camera}</small></div></div></div><p class="controls-caption">${t.gamepad}</p><div class="controls-mapping-grid">${mapping(t.movement,['L'])}${mapping(t.camera,['R'])}${mapping(t.forward,['RT'])}${mapping(t.brake,['LT'])}${mapping(t.interact,['A'])}${mapping(t.vehicle,['Y'])}${mapping(t.reset,['X'])}${mapping(t.return,['B'])}${mapping(t.map,['View'])}${mapping(t.pause,['Start'])}</div></section>
   <section id="control-panel-2" role="tabpanel" aria-labelledby="control-tab-2" hidden><div class="touch-diagram"><div class="touch-device"><div class="touch-landscape"><span class="touch-avatar">♙</span><div class="touch-doc-actions"><span>E · ${t.interact}</span><span>F · ${t.vehicle}</span></div><div class="touch-doc-steer"><b>◀</b><b>▶</b></div><div class="touch-doc-pedals"><span>↓</span><span>■</span><b>↑</b></div></div></div></div><p class="controls-caption">${t.touch}</p><div class="controls-mapping-grid">${mapping(t.movement,['◀','▶'])}${mapping(t.forward,['↑'])}${mapping(t.back,['↓'])}${mapping(t.brake,['■'])}${mapping(t.interact,['E'])}${mapping(t.vehicle,['F'])}</div></section><p class="controls-footnote">${t.note}<br>${t.noCombat}</p>`;
  container.querySelectorAll('[role=tab]').forEach((button,i)=>{button.onclick=()=>select(i);button.onkeydown=event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.code))return;event.preventDefault();event.stopPropagation();select(event.code==='Home'?0:event.code==='End'?2:i+(event.code==='ArrowRight'?1:-1),true);};});
  select(tab);
 }
 render(); return Object.freeze({setLanguage(value){const next=value==='en'?'en':'zh';if(next!==currentLanguage){currentLanguage=next;render();}},selectTab:select,snapshot:()=>({tab,language:currentLanguage})});
}
